version: '1.0'

services: 
  user-service:
    build: .
    container_name: user-service
    ports:
      - "4000:4000"
    depends_on:
      postgres-db: 
        condition: service_started
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Docker
    #   - DOTNET_ENVIRONMENT=Docker
    networks:
      - user-service-local 

  postgres-db:
    restart: always
    image: postgres
    container_name: postgres-container-test
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=userservice
    networks:
      - user-service-local 


networks:
  user-service-local:
    external: false
volumes:
  db-data: